// qa/e2e-selenium/src/test/java/ph/abotkamay/qa/scenarios/DonationScenario.java
package ph.abotkamay.qa.scenarios;

import java.util.List;

/**
 * One end-to-end scenario from the scenario catalog. Scenarios are generated by AI from the acceptance
 * criteria (see ai/generate-scenarios.prompt.md), then reviewed by a human; only APPROVED ones run.
 */
public record DonationScenario(
        String id,
        String title,
        List<String> requirementIds,
        Origin origin,
        Review review,
        List<String> tags,
        RiskLevel riskLevel,
        Input input,
        SandboxOutcome sandboxOutcome,
        Expected expected) {

    public enum Origin { AI_GENERATED, AI_ASSISTED, HUMAN_AUTHORED }

    public enum ReviewStatus { APPROVED, PENDING_REVIEW, REJECTED }

    public enum RiskLevel { LOW, MEDIUM, HIGH, CRITICAL }

    public enum PaymentMethod { GCASH, MAYA, CARD }

    /** What the sandbox checkout does; NOT_REACHED when validation must stop the donor first. */
    public enum SandboxOutcome { AUTHORIZE, FAIL, NOT_REACHED }

    public enum Outcome { RECEIPT, DECLINED, VALIDATION_ERROR }

    public record Review(ReviewStatus status, String reviewedBy, String reviewedAt, String notes) {}

    public record Input(String amount, PaymentMethod paymentMethod, boolean anonymous) {}

    /**
     * @param ledgerAmountMinor expected public-ledger amount in centavos (string, like the API)
     * @param ledgerDonorLabel  how the donor appears in the public ledger ("Anonymous" or masked name)
     * @param messageContains   text the donor must see for DECLINED / VALIDATION_ERROR outcomes
     */
    public record Expected(Outcome outcome, String ledgerAmountMinor, String ledgerDonorLabel, String messageContains) {}

    public boolean isApproved() {
        return review != null && review.status() == ReviewStatus.APPROVED;
    }

    /** Used by JUnit as the display name of each parameterized invocation. */
    @Override
    public String toString() {
        return id + " " + title;
    }
}
